In [86]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [87]:
prices = pd.read_excel('prices_excel.xlsx')

c:\Users\janle\AppData\Local\Programs\Python\Python311\Lib\site-packages\openpyxl\styles\stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

In [88]:
# drop the first rows
prices = prices.drop([0, 1, 2, 3, 4, 5, 6, 7])
#use the first row as header
prices.columns = prices.iloc[0]
prices = prices.drop([8])
prices.reset_index(drop=True, inplace=True)
prices

8,Datum,Anfang,Ende,Deutschland/Luxemburg [€/MWh],∅ Anrainer DE/LU [€/MWh],Belgien [€/MWh],Dänemark 1 [€/MWh],Dänemark 2 [€/MWh],Frankreich [€/MWh],Niederlande [€/MWh],Norwegen 2 [€/MWh],Österreich [€/MWh],Polen [€/MWh],Schweden 4 [€/MWh],Schweiz [€/MWh],Tschechien [€/MWh],DE/AT/LU [€/MWh],Italien (Nord) [€/MWh],Slowenien [€/MWh],Ungarn [€/MWh]
0,01.01.2023,00:00,01:00,-5.17,13.85,-4.39,2.01,2.01,0,-3.61,119.32,12.06,18.09,2.01,0.03,4.84,-,195.9,13.31,19.76
1,01.01.2023,01:00,02:00,-1.07,9.79,-1.75,1.38,1.38,-0.1,-1.46,108.83,-0.1,5.75,1.38,-7.25,-0.35,-,191.09,-0.07,0.19
2,01.01.2023,02:00,03:00,-1.47,8.91,-1.46,0.09,0.09,-1.33,-1.52,102.39,-0.66,5.27,0.09,-3.99,-0.97,-,187.95,-0.47,0.07
3,01.01.2023,03:00,04:00,-5.08,6.58,-5.27,0.08,0.08,-4.08,-5,92.36,-1.99,5.74,0.08,-7.71,-1.93,-,187.82,-1.56,0.01
4,01.01.2023,04:00,05:00,-4.49,5.42,-4.41,0.05,0.05,-4.16,-4.6,82.66,-2.42,5.22,0.05,-9.71,-3.07,-,187.74,-1.94,-0.77
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8755,31.12.2023,19:00,20:00,9,33.2,20.26,39.64,39.64,17.75,39.64,62.88,19.57,46.06,39.64,23.4,16.69,-,136.07,21.49,25.05
8756,31.12.2023,20:00,21:00,7.95,29.6,19.65,34.89,34.89,16.43,34.89,62.6,17.2,35.01,34.89,20.65,14.47,-,130,19.19,23.33
8757,31.12.2023,21:00,22:00,6,22.61,9,29.6,29.6,8.16,13.3,62.25,8.2,41.92,29.6,9.58,7.52,-,117.23,8.71,9.82
8758,31.12.2023,22:00,23:00,10.68,24.2,10.68,28.67,28.67,10.68,10.68,61.77,10.68,48.27,28.67,16.78,10.68,-,108.96,10.68,10.68
8759,31.12.2023,23:00,00:00,2.44,19.26,3.17,26.87,26.87,3.64,3.17,59.31,9.35,35.7,26.87,9.51,7.44,-,106.12,11.02,14.95

In [89]:
#change Datum to datetime format
prices['Date'] = pd.to_datetime(prices['Datum'], format='%d.%m.%Y')
#drop the hour part of date column
prices['Date'] = prices['Date'].dt.date

#get the first half of the string in Anfang column
prices['hour'] = prices['Anfang'].str.split(':').str[0].astype(int)
#drop Datum, Anfang and ende columns
prices = prices.drop(['Datum', 'Anfang', 'Ende'], axis=1)

prices.columns

#drop all prices except Dänemark 1
prices = prices.drop(['Deutschland/Luxemburg [€/MWh]', '∅ Anrainer DE/LU [€/MWh]',
       'Belgien [€/MWh]', 'Dänemark 2 [€/MWh]',
       'Frankreich [€/MWh]', 'Niederlande [€/MWh]', 'Norwegen 2 [€/MWh]',
       'Österreich [€/MWh]', 'Polen [€/MWh]', 'Schweden 4 [€/MWh]',
       'Schweiz [€/MWh]', 'Tschechien [€/MWh]', 'DE/AT/LU [€/MWh]',
       'Italien (Nord) [€/MWh]', 'Slowenien [€/MWh]', 'Ungarn [€/MWh]',], axis=1)

In [91]:
prices

8    Dänemark 1 [€/MWh]        Date  hour
0                  2.01  2023-01-01     0
1                  1.38  2023-01-01     1
2                  0.09  2023-01-01     2
3                  0.08  2023-01-01     3
4                  0.05  2023-01-01     4
...                 ...         ...   ...
8755              39.64  2023-12-31    19
8756              34.89  2023-12-31    20
8757               29.6  2023-12-31    21
8758              28.67  2023-12-31    22
8759              26.87  2023-12-31    23

[8760 rows x 3 columns]

In [90]:
# save as csv
prices.to_csv('prices.csv', index=False)